---

pipelines:
  browser:
    - accepts
    - setLocale
    - fastify-formbody

  api:
    - accepts
    - setLocale

scopes:
  - path: '/api'
    pipeline: browser
    routes:
      - root: 'home#index'
      - resources:
          name: users
          routes:
            - resource: photo

  - path: '/test'
    pipeline: api
    routes:
      - root: 'home#index'

  - path: '/'
    pipeline: browser
    routes:
      - root: 'home#index'

      - resources:
          name: users
          only: ['show']

      - resource:
          name: session
          except: ['build']
          routes:
            - resources: tokens
            - root: 'home#index'

      - resources:
          name: articles
          routes:
            - resources: comments
            - resource:
                name: metadata
                except: ['show']
